// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	// Types that are valid to be assigned to Type:
	//	*Message_Request
	//	*Message_Reply
	//	*Message_Prepare
	//	*Message_Commit
	//	*Message_Prwrapped
	//	*Message_Acknowledge
	//	*Message_Audit
	//	*Message_Loghistory
	//	*Message_Forwardauth
	//	*Message_Challenge
	//	*Message_Evidencetransfer
	Type                 isMessage_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Type interface {
	isMessage_Type()
}

type Message_Request struct {
	Request *Request `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type Message_Reply struct {
	Reply *Reply `protobuf:"bytes,2,opt,name=reply,proto3,oneof"`
}

type Message_Prepare struct {
	Prepare *Prepare `protobuf:"bytes,3,opt,name=prepare,proto3,oneof"`
}

type Message_Commit struct {
	Commit *Commit `protobuf:"bytes,4,opt,name=commit,proto3,oneof"`
}

type Message_Prwrapped struct {
	Prwrapped *PRWrapped `protobuf:"bytes,5,opt,name=prwrapped,proto3,oneof"`
}

type Message_Acknowledge struct {
	Acknowledge *Acknowledge `protobuf:"bytes,6,opt,name=acknowledge,proto3,oneof"`
}

type Message_Audit struct {
	Audit *Audit `protobuf:"bytes,7,opt,name=audit,proto3,oneof"`
}

type Message_Loghistory struct {
	Loghistory *Loghistory `protobuf:"bytes,8,opt,name=loghistory,proto3,oneof"`
}

type Message_Forwardauth struct {
	Forwardauth *ForwardAuth `protobuf:"bytes,9,opt,name=forwardauth,proto3,oneof"`
}

type Message_Challenge struct {
	Challenge *Challenge `protobuf:"bytes,10,opt,name=challenge,proto3,oneof"`
}

type Message_Evidencetransfer struct {
	Evidencetransfer *EvidenceTransfer `protobuf:"bytes,11,opt,name=evidencetransfer,proto3,oneof"`
}

func (*Message_Request) isMessage_Type() {}

func (*Message_Reply) isMessage_Type() {}

func (*Message_Prepare) isMessage_Type() {}

func (*Message_Commit) isMessage_Type() {}

func (*Message_Prwrapped) isMessage_Type() {}

func (*Message_Acknowledge) isMessage_Type() {}

func (*Message_Audit) isMessage_Type() {}

func (*Message_Loghistory) isMessage_Type() {}

func (*Message_Forwardauth) isMessage_Type() {}

func (*Message_Challenge) isMessage_Type() {}

func (*Message_Evidencetransfer) isMessage_Type() {}

func (m *Message) GetType() isMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Message) GetRequest() *Request {
	if x, ok := m.GetType().(*Message_Request); ok {
		return x.Request
	}
	return nil
}

func (m *Message) GetReply() *Reply {
	if x, ok := m.GetType().(*Message_Reply); ok {
		return x.Reply
	}
	return nil
}

func (m *Message) GetPrepare() *Prepare {
	if x, ok := m.GetType().(*Message_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (m *Message) GetCommit() *Commit {
	if x, ok := m.GetType().(*Message_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *Message) GetPrwrapped() *PRWrapped {
	if x, ok := m.GetType().(*Message_Prwrapped); ok {
		return x.Prwrapped
	}
	return nil
}

func (m *Message) GetAcknowledge() *Acknowledge {
	if x, ok := m.GetType().(*Message_Acknowledge); ok {
		return x.Acknowledge
	}
	return nil
}

func (m *Message) GetAudit() *Audit {
	if x, ok := m.GetType().(*Message_Audit); ok {
		return x.Audit
	}
	return nil
}

func (m *Message) GetLoghistory() *Loghistory {
	if x, ok := m.GetType().(*Message_Loghistory); ok {
		return x.Loghistory
	}
	return nil
}

func (m *Message) GetForwardauth() *ForwardAuth {
	if x, ok := m.GetType().(*Message_Forwardauth); ok {
		return x.Forwardauth
	}
	return nil
}

func (m *Message) GetChallenge() *Challenge {
	if x, ok := m.GetType().(*Message_Challenge); ok {
		return x.Challenge
	}
	return nil
}

func (m *Message) GetEvidencetransfer() *EvidenceTransfer {
	if x, ok := m.GetType().(*Message_Evidencetransfer); ok {
		return x.Evidencetransfer
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Request)(nil),
		(*Message_Reply)(nil),
		(*Message_Prepare)(nil),
		(*Message_Commit)(nil),
		(*Message_Prwrapped)(nil),
		(*Message_Acknowledge)(nil),
		(*Message_Audit)(nil),
		(*Message_Loghistory)(nil),
		(*Message_Forwardauth)(nil),
		(*Message_Challenge)(nil),
		(*Message_Evidencetransfer)(nil),
	}
}

type Request struct {
	Msg                  *Request_M `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Signature            []byte     `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMsg() *Request_M {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Request) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Request_M struct {
	ClientId             uint32   `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq                  uint64   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_M) Reset()         { *m = Request_M{} }
func (m *Request_M) String() string { return proto.CompactTextString(m) }
func (*Request_M) ProtoMessage()    {}
func (*Request_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1, 0}
}

func (m *Request_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_M.Unmarshal(m, b)
}
func (m *Request_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_M.Marshal(b, m, deterministic)
}
func (m *Request_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_M.Merge(m, src)
}
func (m *Request_M) XXX_Size() int {
	return xxx_messageInfo_Request_M.Size(m)
}
func (m *Request_M) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_M.DiscardUnknown(m)
}

var xxx_messageInfo_Request_M proto.InternalMessageInfo

func (m *Request_M) GetClientId() uint32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *Request_M) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Request_M) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Reply struct {
	Msg                  *Reply_M `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetMsg() *Reply_M {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Reply) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Reply_M struct {
	ReplicaId            uint32   `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	ClientId             uint32   `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq                  uint64   `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Result               []byte   `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply_M) Reset()         { *m = Reply_M{} }
func (m *Reply_M) String() string { return proto.CompactTextString(m) }
func (*Reply_M) ProtoMessage()    {}
func (*Reply_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2, 0}
}

func (m *Reply_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply_M.Unmarshal(m, b)
}
func (m *Reply_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply_M.Marshal(b, m, deterministic)
}
func (m *Reply_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply_M.Merge(m, src)
}
func (m *Reply_M) XXX_Size() int {
	return xxx_messageInfo_Reply_M.Size(m)
}
func (m *Reply_M) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply_M.DiscardUnknown(m)
}

var xxx_messageInfo_Reply_M proto.InternalMessageInfo

func (m *Reply_M) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Reply_M) GetClientId() uint32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *Reply_M) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Reply_M) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type Prepare struct {
	Msg                  *Prepare_M `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	ReplicaUi            []byte     `protobuf:"bytes,2,opt,name=replica_ui,json=replicaUi,proto3" json:"replica_ui,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Prepare) Reset()         { *m = Prepare{} }
func (m *Prepare) String() string { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()    {}
func (*Prepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *Prepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prepare.Unmarshal(m, b)
}
func (m *Prepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prepare.Marshal(b, m, deterministic)
}
func (m *Prepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prepare.Merge(m, src)
}
func (m *Prepare) XXX_Size() int {
	return xxx_messageInfo_Prepare.Size(m)
}
func (m *Prepare) XXX_DiscardUnknown() {
	xxx_messageInfo_Prepare.DiscardUnknown(m)
}

var xxx_messageInfo_Prepare proto.InternalMessageInfo

func (m *Prepare) GetMsg() *Prepare_M {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Prepare) GetReplicaUi() []byte {
	if m != nil {
		return m.ReplicaUi
	}
	return nil
}

type Prepare_M struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	ReplicaId            uint32   `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Request              *Request `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prepare_M) Reset()         { *m = Prepare_M{} }
func (m *Prepare_M) String() string { return proto.CompactTextString(m) }
func (*Prepare_M) ProtoMessage()    {}
func (*Prepare_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3, 0}
}

func (m *Prepare_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prepare_M.Unmarshal(m, b)
}
func (m *Prepare_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prepare_M.Marshal(b, m, deterministic)
}
func (m *Prepare_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prepare_M.Merge(m, src)
}
func (m *Prepare_M) XXX_Size() int {
	return xxx_messageInfo_Prepare_M.Size(m)
}
func (m *Prepare_M) XXX_DiscardUnknown() {
	xxx_messageInfo_Prepare_M.DiscardUnknown(m)
}

var xxx_messageInfo_Prepare_M proto.InternalMessageInfo

func (m *Prepare_M) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Prepare_M) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Prepare_M) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type Commit struct {
	Msg                  *Commit_M `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	ReplicaUi            []byte    `protobuf:"bytes,2,opt,name=replica_ui,json=replicaUi,proto3" json:"replica_ui,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetMsg() *Commit_M {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Commit) GetReplicaUi() []byte {
	if m != nil {
		return m.ReplicaUi
	}
	return nil
}

type Commit_M struct {
	View                 uint64   `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	ReplicaId            uint32   `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	PrimaryId            uint32   `protobuf:"varint,3,opt,name=primary_id,json=primaryId,proto3" json:"primary_id,omitempty"`
	Request              *Request `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	PrimaryUi            []byte   `protobuf:"bytes,5,opt,name=primary_ui,json=primaryUi,proto3" json:"primary_ui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commit_M) Reset()         { *m = Commit_M{} }
func (m *Commit_M) String() string { return proto.CompactTextString(m) }
func (*Commit_M) ProtoMessage()    {}
func (*Commit_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4, 0}
}

func (m *Commit_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit_M.Unmarshal(m, b)
}
func (m *Commit_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit_M.Marshal(b, m, deterministic)
}
func (m *Commit_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit_M.Merge(m, src)
}
func (m *Commit_M) XXX_Size() int {
	return xxx_messageInfo_Commit_M.Size(m)
}
func (m *Commit_M) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit_M.DiscardUnknown(m)
}

var xxx_messageInfo_Commit_M proto.InternalMessageInfo

func (m *Commit_M) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Commit_M) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Commit_M) GetPrimaryId() uint32 {
	if m != nil {
		return m.PrimaryId
	}
	return 0
}

func (m *Commit_M) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Commit_M) GetPrimaryUi() []byte {
	if m != nil {
		return m.PrimaryUi
	}
	return nil
}

type PRWrapped struct {
	Msg                  *PRWrapped_M `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PRWrapped) Reset()         { *m = PRWrapped{} }
func (m *PRWrapped) String() string { return proto.CompactTextString(m) }
func (*PRWrapped) ProtoMessage()    {}
func (*PRWrapped) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *PRWrapped) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PRWrapped.Unmarshal(m, b)
}
func (m *PRWrapped) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PRWrapped.Marshal(b, m, deterministic)
}
func (m *PRWrapped) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PRWrapped.Merge(m, src)
}
func (m *PRWrapped) XXX_Size() int {
	return xxx_messageInfo_PRWrapped.Size(m)
}
func (m *PRWrapped) XXX_DiscardUnknown() {
	xxx_messageInfo_PRWrapped.DiscardUnknown(m)
}

var xxx_messageInfo_PRWrapped proto.InternalMessageInfo

func (m *PRWrapped) GetMsg() *PRWrapped_M {
	if m != nil {
		return m.Msg
	}
	return nil
}

type PRWrapped_M struct {
	ReplicaId            uint32   `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	PeerId               uint32   `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Prevhash             []byte   `protobuf:"bytes,4,opt,name=prevhash,proto3" json:"prevhash,omitempty"`
	Sequence             uint64   `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Authenticator        []byte   `protobuf:"bytes,6,opt,name=authenticator,proto3" json:"authenticator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PRWrapped_M) Reset()         { *m = PRWrapped_M{} }
func (m *PRWrapped_M) String() string { return proto.CompactTextString(m) }
func (*PRWrapped_M) ProtoMessage()    {}
func (*PRWrapped_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5, 0}
}

func (m *PRWrapped_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PRWrapped_M.Unmarshal(m, b)
}
func (m *PRWrapped_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PRWrapped_M.Marshal(b, m, deterministic)
}
func (m *PRWrapped_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PRWrapped_M.Merge(m, src)
}
func (m *PRWrapped_M) XXX_Size() int {
	return xxx_messageInfo_PRWrapped_M.Size(m)
}
func (m *PRWrapped_M) XXX_DiscardUnknown() {
	xxx_messageInfo_PRWrapped_M.DiscardUnknown(m)
}

var xxx_messageInfo_PRWrapped_M proto.InternalMessageInfo

func (m *PRWrapped_M) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *PRWrapped_M) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *PRWrapped_M) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *PRWrapped_M) GetPrevhash() []byte {
	if m != nil {
		return m.Prevhash
	}
	return nil
}

func (m *PRWrapped_M) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *PRWrapped_M) GetAuthenticator() []byte {
	if m != nil {
		return m.Authenticator
	}
	return nil
}

type Acknowledge struct {
	Msg                  *Acknowledge_M `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Acknowledge) Reset()         { *m = Acknowledge{} }
func (m *Acknowledge) String() string { return proto.CompactTextString(m) }
func (*Acknowledge) ProtoMessage()    {}
func (*Acknowledge) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}

func (m *Acknowledge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Acknowledge.Unmarshal(m, b)
}
func (m *Acknowledge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Acknowledge.Marshal(b, m, deterministic)
}
func (m *Acknowledge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Acknowledge.Merge(m, src)
}
func (m *Acknowledge) XXX_Size() int {
	return xxx_messageInfo_Acknowledge.Size(m)
}
func (m *Acknowledge) XXX_DiscardUnknown() {
	xxx_messageInfo_Acknowledge.DiscardUnknown(m)
}

var xxx_messageInfo_Acknowledge proto.InternalMessageInfo

func (m *Acknowledge) GetMsg() *Acknowledge_M {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Acknowledge_M struct {
	ReplicaId            uint32   `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	PeerId               uint32   `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Prevhash             []byte   `protobuf:"bytes,3,opt,name=prevhash,proto3" json:"prevhash,omitempty"`
	Sequence             uint64   `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Authenticator        []byte   `protobuf:"bytes,5,opt,name=authenticator,proto3" json:"authenticator,omitempty"`
	Msg                  []byte   `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	Origseq              uint64   `protobuf:"varint,7,opt,name=origseq,proto3" json:"origseq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Acknowledge_M) Reset()         { *m = Acknowledge_M{} }
func (m *Acknowledge_M) String() string { return proto.CompactTextString(m) }
func (*Acknowledge_M) ProtoMessage()    {}
func (*Acknowledge_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6, 0}
}

func (m *Acknowledge_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Acknowledge_M.Unmarshal(m, b)
}
func (m *Acknowledge_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Acknowledge_M.Marshal(b, m, deterministic)
}
func (m *Acknowledge_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Acknowledge_M.Merge(m, src)
}
func (m *Acknowledge_M) XXX_Size() int {
	return xxx_messageInfo_Acknowledge_M.Size(m)
}
func (m *Acknowledge_M) XXX_DiscardUnknown() {
	xxx_messageInfo_Acknowledge_M.DiscardUnknown(m)
}

var xxx_messageInfo_Acknowledge_M proto.InternalMessageInfo

func (m *Acknowledge_M) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Acknowledge_M) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *Acknowledge_M) GetPrevhash() []byte {
	if m != nil {
		return m.Prevhash
	}
	return nil
}

func (m *Acknowledge_M) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Acknowledge_M) GetAuthenticator() []byte {
	if m != nil {
		return m.Authenticator
	}
	return nil
}

func (m *Acknowledge_M) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Acknowledge_M) GetOrigseq() uint64 {
	if m != nil {
		return m.Origseq
	}
	return 0
}

type Audit struct {
	Msg                  *Audit_M `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Audit) Reset()         { *m = Audit{} }
func (m *Audit) String() string { return proto.CompactTextString(m) }
func (*Audit) ProtoMessage()    {}
func (*Audit) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{7}
}

func (m *Audit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Audit.Unmarshal(m, b)
}
func (m *Audit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Audit.Marshal(b, m, deterministic)
}
func (m *Audit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Audit.Merge(m, src)
}
func (m *Audit) XXX_Size() int {
	return xxx_messageInfo_Audit.Size(m)
}
func (m *Audit) XXX_DiscardUnknown() {
	xxx_messageInfo_Audit.DiscardUnknown(m)
}

var xxx_messageInfo_Audit proto.InternalMessageInfo

func (m *Audit) GetMsg() *Audit_M {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Audit_M struct {
	ReplicaId            uint32   `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	PeerId               uint32   `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Prevhash             []byte   `protobuf:"bytes,4,opt,name=prevhash,proto3" json:"prevhash,omitempty"`
	Sequence             uint64   `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Authenticator        []byte   `protobuf:"bytes,6,opt,name=authenticator,proto3" json:"authenticator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Audit_M) Reset()         { *m = Audit_M{} }
func (m *Audit_M) String() string { return proto.CompactTextString(m) }
func (*Audit_M) ProtoMessage()    {}
func (*Audit_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{7, 0}
}

func (m *Audit_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Audit_M.Unmarshal(m, b)
}
func (m *Audit_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Audit_M.Marshal(b, m, deterministic)
}
func (m *Audit_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Audit_M.Merge(m, src)
}
func (m *Audit_M) XXX_Size() int {
	return xxx_messageInfo_Audit_M.Size(m)
}
func (m *Audit_M) XXX_DiscardUnknown() {
	xxx_messageInfo_Audit_M.DiscardUnknown(m)
}

var xxx_messageInfo_Audit_M proto.InternalMessageInfo

func (m *Audit_M) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Audit_M) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *Audit_M) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Audit_M) GetPrevhash() []byte {
	if m != nil {
		return m.Prevhash
	}
	return nil
}

func (m *Audit_M) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Audit_M) GetAuthenticator() []byte {
	if m != nil {
		return m.Authenticator
	}
	return nil
}

type Loghistory struct {
	Msg                  *Loghistory_M `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Loghistory) Reset()         { *m = Loghistory{} }
func (m *Loghistory) String() string { return proto.CompactTextString(m) }
func (*Loghistory) ProtoMessage()    {}
func (*Loghistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{8}
}

func (m *Loghistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Loghistory.Unmarshal(m, b)
}
func (m *Loghistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Loghistory.Marshal(b, m, deterministic)
}
func (m *Loghistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Loghistory.Merge(m, src)
}
func (m *Loghistory) XXX_Size() int {
	return xxx_messageInfo_Loghistory.Size(m)
}
func (m *Loghistory) XXX_DiscardUnknown() {
	xxx_messageInfo_Loghistory.DiscardUnknown(m)
}

var xxx_messageInfo_Loghistory proto.InternalMessageInfo

func (m *Loghistory) GetMsg() *Loghistory_M {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Loghistory_M struct {
	ReplicaId            uint32   `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	PeerId               uint32   `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Sequence             uint64   `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Logs                 []byte   `protobuf:"bytes,4,opt,name=logs,proto3" json:"logs,omitempty"`
	Hash                 []byte   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Loghistory_M) Reset()         { *m = Loghistory_M{} }
func (m *Loghistory_M) String() string { return proto.CompactTextString(m) }
func (*Loghistory_M) ProtoMessage()    {}
func (*Loghistory_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{8, 0}
}

func (m *Loghistory_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Loghistory_M.Unmarshal(m, b)
}
func (m *Loghistory_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Loghistory_M.Marshal(b, m, deterministic)
}
func (m *Loghistory_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Loghistory_M.Merge(m, src)
}
func (m *Loghistory_M) XXX_Size() int {
	return xxx_messageInfo_Loghistory_M.Size(m)
}
func (m *Loghistory_M) XXX_DiscardUnknown() {
	xxx_messageInfo_Loghistory_M.DiscardUnknown(m)
}

var xxx_messageInfo_Loghistory_M proto.InternalMessageInfo

func (m *Loghistory_M) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Loghistory_M) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *Loghistory_M) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Loghistory_M) GetLogs() []byte {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *Loghistory_M) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ForwardAuth struct {
	Msg                  *ForwardAuth_M `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ForwardAuth) Reset()         { *m = ForwardAuth{} }
func (m *ForwardAuth) String() string { return proto.CompactTextString(m) }
func (*ForwardAuth) ProtoMessage()    {}
func (*ForwardAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{9}
}

func (m *ForwardAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardAuth.Unmarshal(m, b)
}
func (m *ForwardAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardAuth.Marshal(b, m, deterministic)
}
func (m *ForwardAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardAuth.Merge(m, src)
}
func (m *ForwardAuth) XXX_Size() int {
	return xxx_messageInfo_ForwardAuth.Size(m)
}
func (m *ForwardAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardAuth.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardAuth proto.InternalMessageInfo

func (m *ForwardAuth) GetMsg() *ForwardAuth_M {
	if m != nil {
		return m.Msg
	}
	return nil
}

type ForwardAuth_M struct {
	ReplicaId            uint32   `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	PeerId               uint32   `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Sequence             uint64   `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Authenticator        []byte   `protobuf:"bytes,4,opt,name=authenticator,proto3" json:"authenticator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardAuth_M) Reset()         { *m = ForwardAuth_M{} }
func (m *ForwardAuth_M) String() string { return proto.CompactTextString(m) }
func (*ForwardAuth_M) ProtoMessage()    {}
func (*ForwardAuth_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{9, 0}
}

func (m *ForwardAuth_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardAuth_M.Unmarshal(m, b)
}
func (m *ForwardAuth_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardAuth_M.Marshal(b, m, deterministic)
}
func (m *ForwardAuth_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardAuth_M.Merge(m, src)
}
func (m *ForwardAuth_M) XXX_Size() int {
	return xxx_messageInfo_ForwardAuth_M.Size(m)
}
func (m *ForwardAuth_M) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardAuth_M.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardAuth_M proto.InternalMessageInfo

func (m *ForwardAuth_M) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *ForwardAuth_M) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *ForwardAuth_M) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ForwardAuth_M) GetAuthenticator() []byte {
	if m != nil {
		return m.Authenticator
	}
	return nil
}

type Challenge struct {
	Msg                  *Challenge_M `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Challenge) Reset()         { *m = Challenge{} }
func (m *Challenge) String() string { return proto.CompactTextString(m) }
func (*Challenge) ProtoMessage()    {}
func (*Challenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{10}
}

func (m *Challenge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Challenge.Unmarshal(m, b)
}
func (m *Challenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Challenge.Marshal(b, m, deterministic)
}
func (m *Challenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Challenge.Merge(m, src)
}
func (m *Challenge) XXX_Size() int {
	return xxx_messageInfo_Challenge.Size(m)
}
func (m *Challenge) XXX_DiscardUnknown() {
	xxx_messageInfo_Challenge.DiscardUnknown(m)
}

var xxx_messageInfo_Challenge proto.InternalMessageInfo

func (m *Challenge) GetMsg() *Challenge_M {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Challenge_M struct {
	ReplicaId            uint32   `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	PeerId               uint32   `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	FaultyId             uint32   `protobuf:"varint,3,opt,name=faulty_id,json=faultyId,proto3" json:"faulty_id,omitempty"`
	Ctype                uint32   `protobuf:"varint,4,opt,name=ctype,proto3" json:"ctype,omitempty"`
	Origmsg              []byte   `protobuf:"bytes,5,opt,name=origmsg,proto3" json:"origmsg,omitempty"`
	Sequence             uint64   `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Challenge_M) Reset()         { *m = Challenge_M{} }
func (m *Challenge_M) String() string { return proto.CompactTextString(m) }
func (*Challenge_M) ProtoMessage()    {}
func (*Challenge_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{10, 0}
}

func (m *Challenge_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Challenge_M.Unmarshal(m, b)
}
func (m *Challenge_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Challenge_M.Marshal(b, m, deterministic)
}
func (m *Challenge_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Challenge_M.Merge(m, src)
}
func (m *Challenge_M) XXX_Size() int {
	return xxx_messageInfo_Challenge_M.Size(m)
}
func (m *Challenge_M) XXX_DiscardUnknown() {
	xxx_messageInfo_Challenge_M.DiscardUnknown(m)
}

var xxx_messageInfo_Challenge_M proto.InternalMessageInfo

func (m *Challenge_M) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Challenge_M) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *Challenge_M) GetFaultyId() uint32 {
	if m != nil {
		return m.FaultyId
	}
	return 0
}

func (m *Challenge_M) GetCtype() uint32 {
	if m != nil {
		return m.Ctype
	}
	return 0
}

func (m *Challenge_M) GetOrigmsg() []byte {
	if m != nil {
		return m.Origmsg
	}
	return nil
}

func (m *Challenge_M) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

type EvidenceTransfer struct {
	Msg                  *EvidenceTransfer_M `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *EvidenceTransfer) Reset()         { *m = EvidenceTransfer{} }
func (m *EvidenceTransfer) String() string { return proto.CompactTextString(m) }
func (*EvidenceTransfer) ProtoMessage()    {}
func (*EvidenceTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{11}
}

func (m *EvidenceTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvidenceTransfer.Unmarshal(m, b)
}
func (m *EvidenceTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvidenceTransfer.Marshal(b, m, deterministic)
}
func (m *EvidenceTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvidenceTransfer.Merge(m, src)
}
func (m *EvidenceTransfer) XXX_Size() int {
	return xxx_messageInfo_EvidenceTransfer.Size(m)
}
func (m *EvidenceTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_EvidenceTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_EvidenceTransfer proto.InternalMessageInfo

func (m *EvidenceTransfer) GetMsg() *EvidenceTransfer_M {
	if m != nil {
		return m.Msg
	}
	return nil
}

type EvidenceTransfer_M struct {
	ReplicaId            uint32   `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	PeerId               uint32   `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	FaultyId             uint32   `protobuf:"varint,3,opt,name=faulty_id,json=faultyId,proto3" json:"faulty_id,omitempty"`
	Faulttype            uint32   `protobuf:"varint,4,opt,name=faulttype,proto3" json:"faulttype,omitempty"`
	Proof                []byte   `protobuf:"bytes,5,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvidenceTransfer_M) Reset()         { *m = EvidenceTransfer_M{} }
func (m *EvidenceTransfer_M) String() string { return proto.CompactTextString(m) }
func (*EvidenceTransfer_M) ProtoMessage()    {}
func (*EvidenceTransfer_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{11, 0}
}

func (m *EvidenceTransfer_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvidenceTransfer_M.Unmarshal(m, b)
}
func (m *EvidenceTransfer_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvidenceTransfer_M.Marshal(b, m, deterministic)
}
func (m *EvidenceTransfer_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvidenceTransfer_M.Merge(m, src)
}
func (m *EvidenceTransfer_M) XXX_Size() int {
	return xxx_messageInfo_EvidenceTransfer_M.Size(m)
}
func (m *EvidenceTransfer_M) XXX_DiscardUnknown() {
	xxx_messageInfo_EvidenceTransfer_M.DiscardUnknown(m)
}

var xxx_messageInfo_EvidenceTransfer_M proto.InternalMessageInfo

func (m *EvidenceTransfer_M) GetReplicaId() uint32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *EvidenceTransfer_M) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *EvidenceTransfer_M) GetFaultyId() uint32 {
	if m != nil {
		return m.FaultyId
	}
	return 0
}

func (m *EvidenceTransfer_M) GetFaulttype() uint32 {
	if m != nil {
		return m.Faulttype
	}
	return 0
}

func (m *EvidenceTransfer_M) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "protobuf.Message")
	proto.RegisterType((*Request)(nil), "protobuf.Request")
	proto.RegisterType((*Request_M)(nil), "protobuf.Request.M")
	proto.RegisterType((*Reply)(nil), "protobuf.Reply")
	proto.RegisterType((*Reply_M)(nil), "protobuf.Reply.M")
	proto.RegisterType((*Prepare)(nil), "protobuf.Prepare")
	proto.RegisterType((*Prepare_M)(nil), "protobuf.Prepare.M")
	proto.RegisterType((*Commit)(nil), "protobuf.Commit")
	proto.RegisterType((*Commit_M)(nil), "protobuf.Commit.M")
	proto.RegisterType((*PRWrapped)(nil), "protobuf.PRWrapped")
	proto.RegisterType((*PRWrapped_M)(nil), "protobuf.PRWrapped.M")
	proto.RegisterType((*Acknowledge)(nil), "protobuf.Acknowledge")
	proto.RegisterType((*Acknowledge_M)(nil), "protobuf.Acknowledge.M")
	proto.RegisterType((*Audit)(nil), "protobuf.Audit")
	proto.RegisterType((*Audit_M)(nil), "protobuf.Audit.M")
	proto.RegisterType((*Loghistory)(nil), "protobuf.Loghistory")
	proto.RegisterType((*Loghistory_M)(nil), "protobuf.Loghistory.M")
	proto.RegisterType((*ForwardAuth)(nil), "protobuf.ForwardAuth")
	proto.RegisterType((*ForwardAuth_M)(nil), "protobuf.ForwardAuth.M")
	proto.RegisterType((*Challenge)(nil), "protobuf.Challenge")
	proto.RegisterType((*Challenge_M)(nil), "protobuf.Challenge.M")
	proto.RegisterType((*EvidenceTransfer)(nil), "protobuf.EvidenceTransfer")
	proto.RegisterType((*EvidenceTransfer_M)(nil), "protobuf.EvidenceTransfer.M")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 901 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xcd, 0x8e, 0xdc, 0x44,
	0x10, 0x1e, 0xaf, 0x3d, 0xf6, 0xb8, 0x66, 0x16, 0x36, 0x9d, 0x3f, 0x6b, 0xb2, 0x91, 0x90, 0x09,
	0x4a, 0x00, 0x31, 0x07, 0x22, 0x21, 0x71, 0x5c, 0x22, 0x90, 0x57, 0xca, 0x4a, 0xa8, 0x45, 0xc4,
	0x11, 0x75, 0xec, 0x1e, 0x4f, 0x0b, 0x8f, 0xed, 0xb4, 0xed, 0x5d, 0xcd, 0x01, 0xc1, 0x03, 0xf0,
	0x08, 0x5c, 0x90, 0xb8, 0x71, 0x05, 0xf1, 0x04, 0x9c, 0x11, 0x57, 0xb8, 0xf1, 0x06, 0xbc, 0x01,
	0xea, 0x1f, 0xdb, 0x3d, 0xde, 0x19, 0xb2, 0x62, 0x95, 0x03, 0xa7, 0x75, 0xd5, 0xf7, 0x75, 0xed,
	0xf7, 0x95, 0xcb, 0xd5, 0x03, 0xaf, 0xad, 0x69, 0x55, 0x91, 0x94, 0x56, 0x8b, 0x92, 0x17, 0x75,
	0x81, 0x26, 0xf2, 0xcf, 0xf3, 0x66, 0x19, 0xfe, 0xe6, 0x80, 0x77, 0xa6, 0x40, 0xf4, 0x1e, 0x78,
	0x9c, 0xbe, 0x68, 0x68, 0x55, 0x07, 0xd6, 0x1b, 0xd6, 0xa3, 0xe9, 0xfb, 0x37, 0x16, 0x2d, 0x6f,
	0x81, 0x15, 0x10, 0x8d, 0x70, 0xcb, 0x41, 0x0f, 0x61, 0xcc, 0x69, 0x99, 0x6d, 0x82, 0x03, 0x49,
	0x7e, 0xdd, 0x24, 0x97, 0xd9, 0x26, 0x1a, 0x61, 0x85, 0x8b, 0xba, 0x25, 0xa7, 0x25, 0xe1, 0x34,
	0xb0, 0x87, 0x75, 0x3f, 0x55, 0x80, 0xa8, 0xab, 0x39, 0xe8, 0x1d, 0x70, 0xe3, 0x62, 0xbd, 0x66,
	0x75, 0xe0, 0x48, 0xf6, 0x51, 0xcf, 0x7e, 0x22, 0xf3, 0xd1, 0x08, 0x6b, 0x06, 0x7a, 0x0c, 0x7e,
	0xc9, 0x2f, 0x38, 0x29, 0x4b, 0x9a, 0x04, 0x63, 0x49, 0xbf, 0x69, 0x14, 0xc7, 0x9f, 0x2b, 0x28,
	0x1a, 0xe1, 0x9e, 0x87, 0x3e, 0x84, 0x29, 0x89, 0xbf, 0xcc, 0x8b, 0x8b, 0x8c, 0x26, 0x29, 0x0d,
	0x5c, 0x79, 0xec, 0x76, 0x7f, 0xec, 0xa4, 0x07, 0xa3, 0x11, 0x36, 0xb9, 0xc2, 0x33, 0x69, 0x12,
	0x56, 0x07, 0xde, 0xd0, 0xf3, 0x89, 0x48, 0x0b, 0xcf, 0x12, 0x47, 0x1f, 0x00, 0x64, 0x45, 0xba,
	0x62, 0x55, 0x5d, 0xf0, 0x4d, 0x30, 0x91, 0xec, 0x5b, 0x3d, 0xfb, 0x69, 0x87, 0x45, 0x23, 0x6c,
	0x30, 0x85, 0xb6, 0x65, 0xc1, 0x2f, 0x08, 0x4f, 0x48, 0x53, 0xaf, 0x02, 0x7f, 0xa8, 0xed, 0x13,
	0x05, 0x9e, 0x34, 0xf5, 0x4a, 0x68, 0x33, 0xb8, 0xa2, 0x17, 0xf1, 0x8a, 0x64, 0x19, 0xcd, 0x53,
	0x1a, 0xc0, 0xb0, 0x17, 0x4f, 0x5a, 0x48, 0xf4, 0xa2, 0xe3, 0xa1, 0x08, 0x8e, 0xe8, 0x39, 0x4b,
	0x68, 0x1e, 0xd3, 0x9a, 0x93, 0xbc, 0x5a, 0x52, 0x1e, 0x4c, 0xe5, 0xd9, 0x79, 0x7f, 0xf6, 0x63,
	0xcd, 0xf8, 0x4c, 0x33, 0xa2, 0x11, 0xbe, 0x74, 0xea, 0x23, 0x17, 0x9c, 0x7a, 0x53, 0xd2, 0xf0,
	0x3b, 0x0b, 0x3c, 0x3d, 0x2d, 0xe8, 0x2d, 0xb0, 0xd7, 0x55, 0xaa, 0xa7, 0xe9, 0xe6, 0xa5, 0x69,
	0x5a, 0x9c, 0x61, 0x81, 0xa3, 0x63, 0xf0, 0x2b, 0x96, 0xe6, 0xa4, 0x6e, 0x38, 0x95, 0xd3, 0x34,
	0xc3, 0x7d, 0x62, 0xfe, 0x14, 0xac, 0x33, 0x74, 0x0f, 0xfc, 0x38, 0x63, 0x34, 0xaf, 0xbf, 0x60,
	0x89, 0xac, 0x77, 0x88, 0x27, 0x2a, 0x71, 0x9a, 0xa0, 0x23, 0xb0, 0x2b, 0xfa, 0x42, 0x9e, 0x74,
	0xb0, 0x78, 0x44, 0x01, 0x78, 0x25, 0xd9, 0x64, 0x05, 0x49, 0xe4, 0xc8, 0xcd, 0x70, 0x1b, 0x86,
	0x3f, 0x5b, 0x30, 0x96, 0xf3, 0x89, 0xde, 0x34, 0xc5, 0xdd, 0x18, 0x4c, 0xef, 0xd5, 0xa4, 0x31,
	0x21, 0xed, 0x3e, 0x80, 0x98, 0x73, 0x16, 0x93, 0x5e, 0x9b, 0xaf, 0x33, 0xa7, 0xc9, 0xb6, 0xf2,
	0x83, 0xdd, 0xca, 0xed, 0x5e, 0xf9, 0x1d, 0x70, 0x39, 0xad, 0x9a, 0x4c, 0x4d, 0xff, 0x0c, 0xeb,
	0x28, 0xfc, 0xc9, 0x02, 0x4f, 0x7f, 0x2c, 0x7b, 0xdb, 0xaa, 0xf1, 0x56, 0xbb, 0x21, 0xac, 0x61,
	0xad, 0x78, 0x9d, 0x79, 0xc6, 0xe6, 0xb1, 0x10, 0x8f, 0xc0, 0x39, 0x67, 0xf4, 0x42, 0xd6, 0x72,
	0xb0, 0x7c, 0x1e, 0x18, 0x3a, 0x18, 0x1a, 0x7a, 0xb7, 0x5f, 0x13, 0xf6, 0x9e, 0x35, 0xd1, 0x2d,
	0x89, 0xf0, 0x6f, 0x0b, 0x5c, 0xf5, 0xd5, 0xa2, 0x07, 0xa6, 0x6a, 0x34, 0xfc, 0xa8, 0xaf, 0x28,
	0xfa, 0x7b, 0xeb, 0x3f, 0xaa, 0xbe, 0x0f, 0x50, 0x72, 0xb6, 0x26, 0x7c, 0x23, 0x60, 0x5b, 0xc1,
	0x3a, 0xb3, 0x6d, 0xca, 0x79, 0x99, 0x29, 0xb3, 0x56, 0xc3, 0xe4, 0xda, 0x99, 0x75, 0xb5, 0x9e,
	0xb1, 0xf0, 0x2f, 0x0b, 0xfc, 0x6e, 0xf5, 0xa0, 0x87, 0xa6, 0xed, 0xdb, 0x3b, 0x96, 0x93, 0x76,
	0x3e, 0xff, 0xd1, 0xba, 0xc2, 0x34, 0xdd, 0x05, 0xaf, 0xa4, 0x94, 0xf7, 0x16, 0x5d, 0x11, 0xaa,
	0x49, 0x12, 0xff, 0x46, 0x4d, 0xbb, 0xec, 0xe4, 0x1c, 0x26, 0x25, 0xa7, 0xe7, 0x2b, 0x52, 0xad,
	0xf4, 0x2c, 0x75, 0xb1, 0xc0, 0x2a, 0x61, 0x26, 0x8f, 0xa9, 0xd4, 0xef, 0xe0, 0x2e, 0x46, 0x0f,
	0xe0, 0x50, 0xec, 0x13, 0x9a, 0xd7, 0x2c, 0x26, 0x75, 0xc1, 0xe5, 0x82, 0x9c, 0xe1, 0xed, 0x64,
	0xf8, 0xcd, 0x01, 0x4c, 0x8d, 0x45, 0x89, 0xde, 0x36, 0x6d, 0xde, 0xdd, 0xb9, 0x4c, 0x5b, 0xa3,
	0xbf, 0x5e, 0xcb, 0xa8, 0x69, 0xcb, 0xfe, 0x17, 0x5b, 0xce, 0xcb, 0x6c, 0x8d, 0x77, 0xd8, 0x6a,
	0xdb, 0xe8, 0xf6, 0x6d, 0x0c, 0xc0, 0x2b, 0x38, 0x4b, 0xc5, 0x67, 0xea, 0xc9, 0x92, 0x6d, 0x18,
	0xfe, 0x61, 0xc1, 0x58, 0xae, 0xfd, 0xbd, 0xab, 0x44, 0xa2, 0xff, 0xcf, 0xf7, 0xfb, 0x8b, 0x05,
	0xd0, 0xdf, 0x52, 0xe8, 0x91, 0xe9, 0xf0, 0xce, 0xae, 0x8b, 0xac, 0xb5, 0xf9, 0xf5, 0x35, 0x5f,
	0x6e, 0xa7, 0xdb, 0x1e, 0xe8, 0x46, 0xe0, 0x64, 0x45, 0x5a, 0x69, 0xaf, 0xf2, 0x59, 0xe4, 0xa4,
	0x7f, 0xf5, 0x2e, 0xe5, 0xb3, 0x50, 0x3e, 0x35, 0xae, 0xc9, 0xbd, 0x93, 0x69, 0x70, 0x5a, 0xed,
	0x5f, 0xbd, 0x2a, 0xed, 0x97, 0x7a, 0xee, 0xec, 0xea, 0xf9, 0x9f, 0x16, 0xf8, 0xdd, 0x3d, 0xbd,
	0x77, 0x71, 0x74, 0x8c, 0x56, 0xf5, 0x0f, 0xd7, 0x1a, 0xac, 0x7b, 0xe0, 0x2f, 0x49, 0x93, 0xd5,
	0xc6, 0x5e, 0x9c, 0xa8, 0xc4, 0x69, 0x82, 0x6e, 0xc1, 0x38, 0x16, 0xb7, 0xba, 0xd4, 0x7b, 0x88,
	0x55, 0xd0, 0x7e, 0x12, 0x42, 0x9d, 0x6a, 0x7c, 0x1b, 0x6e, 0xf5, 0xc0, 0xdd, 0xee, 0x41, 0xf8,
	0xbb, 0x05, 0x47, 0xc3, 0x5f, 0x12, 0x68, 0x61, 0x9a, 0x3c, 0xde, 0xff, 0x93, 0xa3, 0xf5, 0xfa,
	0xed, 0xab, 0xf3, 0x7a, 0xac, 0x41, 0xc3, 0x6f, 0x9f, 0x10, 0x9d, 0x28, 0x79, 0x51, 0x2c, 0xb5,
	0x63, 0x15, 0x3c, 0x77, 0xa5, 0xe0, 0xc7, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x02, 0xb2,
	0x39, 0x61, 0x0b, 0x00, 0x00,
}
